"""Turn the PC server's state into SQL for the Cloudflare D1 database.

Keeping the SAME serverId matters: the phones carry it, and a different one makes every phone do a
"first sync", which merges by rules meant for a brand-new device. Same id = they just carry on.

The Oura refresh tokens go in too, so nobody has to reconnect Oura after the move.

    python tools/export_to_cloud.py
    -> private/migrate.sql   (gitignored: it contains Oura refresh tokens)
"""
import json, os

DATA = os.environ.get('CENTURION_DATA', r'C:\Users\Scene\CenturionData')
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'private', 'migrate.sql')
SEP = '\x00'


def q(v):
    """SQL literal. D1 takes \\u0000 inside a string badly, so entry ids are stored with a real NUL
    written as an escape-free concatenation instead."""
    if v is None:
        return 'NULL'
    return "'" + str(v).replace("'", "''") + "'"


def eid_sql(k, s):
    return f"{q(k)} || char(0) || {q(s)}"


def main():
    state = json.load(open(os.path.join(DATA, 'state.json'), encoding='utf-8'))
    tokens = {}
    try:
        tokens = json.load(open(os.path.join(DATA, 'oura_tokens.json'), encoding='utf-8'))
    except FileNotFoundError:
        pass

    lines = ['-- Centurion: PC server -> Cloudflare D1. Generated by tools/export_to_cloud.py',
             'DELETE FROM entries;', 'DELETE FROM meta;', 'DELETE FROM oura;',
             f"INSERT INTO meta (key, value) VALUES ('serverId', {q(state['serverId'])});",
             f"INSERT INTO meta (key, value) VALUES ('rev', {q(state['rev'])});"]

    for eid, e in state['entries'].items():
        k, _, s = eid.partition(SEP)
        lines.append(
            'INSERT INTO entries (eid, k, s, v, d, rev, by, at) VALUES ('
            f"{eid_sql(k, s)}, {q(k)}, {q(s)}, {q(json.dumps(e['v']))}, {1 if e.get('d') else 0}, "
            f"{int(e['rev'])}, {q(e.get('by'))}, {q(e.get('at'))});")

    for user, t in tokens.items():
        lines.append(
            'INSERT INTO oura (user, access_token, refresh_token, expires_at, scope, linked_at) VALUES ('
            f"{q(user)}, {q(t.get('access_token'))}, {q(t.get('refresh_token'))}, "
            f"{float(t.get('expires_at') or 0)}, {q(t.get('scope'))}, {q(t.get('linked_at'))});")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')
    print(f"{OUT}\n  {len(state['entries'])} entries, rev {state['rev']}, "
          f"serverId {state['serverId'][:8]}…, oura links: {', '.join(tokens) or 'none'}")


if __name__ == '__main__':
    main()
